### PR TITLE
Fix starvation when Signal instances are dropped

### LINKED ISSUE #36: Dropping an instance of `Signal` starves all other open instances using the same event loop
Currently, the global pipe which is used to deliver signal notifications from the signal handler is [unconditionally unregistered from its event loop](https://github.com/alexcrichton/tokio-signal/blob/f67d025325ab8196067d72bedc069cff2781a2fd/src/unix.rs#L212-L215) whenever a `Signal` instance is dropped.

Until another `Signal` instance is created, no more notifications will get delivered which will starve any dependent futures.

Originally reported in alexcrichton/tokio-process#42, a constrained test case exhibiting the behavior is below:

```rust
#![cfg(unix)]

extern crate futures;
extern crate libc;
extern crate tokio;
extern crate tokio_core;
extern crate tokio_signal;

use futures::stream::Stream;
use futures::Future;
use tokio_signal::unix::Signal;
use std::time::{Duration, Instant};

#[test]
fn dropping_signal_does_not_deregister_any_other_instances() {
    // NB: Deadline requires a timer registration which is provided by
    // tokio's `current_thread::Runtime`, but isn't available by just using
    // tokio's default CurrentThread executor which powers `current_thread::block_on_all`.
    let mut rt = tokio::runtime::current_thread::Runtime::new()
        .expect("failed to init runtime");

    rt.spawn(futures::lazy(|| {
        let register_duplicate_signal  = Signal::new(libc::SIGUSR1);
        let register_irrelevant_signal = Signal::new(libc::SIGUSR2); // NB: intentially different signal
        let register_signal            = Signal::new(libc::SIGUSR1);

        register_duplicate_signal.join3(register_irrelevant_signal, register_signal)
            .map_err(|e| panic!("{}", e))
            .and_then(|(dup_signal, irrelevant_signal, signal)| {
                drop(dup_signal);
                drop(irrelevant_signal);

                unsafe { assert_eq!(libc::kill(libc::getpid(), libc::SIGUSR1), 0); }

                let future = signal.into_future()
                    .map_err(|(e, _)| e);

                let deadline_time = Instant::now() + Duration::from_secs(1);
                tokio::timer::Deadline::new(future, deadline_time)
                    .map(|_| ())
                    .map_err(|e| panic!("{}", e))
            })
    }));

    rt.run().expect("running to completion failed");
}
```

### PR DESCRIPTION
**Pull request by ipetkov**
## Issue
* Currently, whenever a new signal stream is created we attempt to register a global pipe with the event loop to drive events.
* We also (correctly) swallow any descriptor-already-registered errors since the same pipe is always used
* However, we currently *deregister* the same global pipe *any time* a Signal stream is dropped.
* This means that if 2 or more of Signal instances exist simultaneously (even if listening for different signals) and one of them is dropped, the remainder will starve (until any new signal is created again).

## The Solution
* We can introduce a new global structure which keeps track of how many signal streams have been registered with a given event loop (the event loop is identified by its OS file descriptor) and only perform a deregistration if all Signal streams have gone away.

## Alternative Solutions
* Simply never deregister the global evented pipe: This is the simplest approach, though if all Signal consumers of one particular event loop go away, it will continue to receive readiness events for other signals that may come in, which would lead to additional processing over head for the reactor

Fixes #36

### CODE REVIEW

**Comment by ipetkov** [comment]
Hmm, I can't understand why the CI is failing on Linux. Tests pass locally on my macOS machine and within a Ubuntu VM...

File: src/unix.rs [hunk 1]
```diff
@@ -191,14 +196,35 @@ impl Evented for EventedReceiver {
...
+        }
+
+        let mut guard = globals.pollfd_register_count.lock().expect("poisoned");
+        match guard.entry(poll.as_raw_fd()) {
+            Entry::Occupied(mut occupied) => {
+                let mut val = occupied.get_mut();
+                *val = val.saturating_add(1);
+            },
+            Entry::Vacant(vacant) => {
+                vacant.insert(1);
```
Comment (alexcrichton) [inline src/unix.rs]: I think it's safe to say that it's impossible for this to overflow, so this can probably just be:

```rust
*globals.pollfd_register_count
    .lock()
    .expect("poisoned")
    .entry(poll.as_raw_fd())
    .or_insert(0) += 1;
```

(similarly below)

**Comment by alexcrichton** [comment]
Hm that is indeed an odd failure! I can reproduce it locally myself. 

The edited strace logs of the failure looks like:

```
4997  socketpair(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0, [6, 7]) = 0
      ...
4997  epoll_ctl(3, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=0, u64=0}}) = 0
4997  ...
4997  epoll_ctl(3, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=4194305, u64=4194305}}) = -1 EEXIST (File exists)
4997  epoll_ctl(3, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=8388610, u64=8388610}}) = -1 EEXIST (File exists)
4997  kill(4996, SIGUSR1 <unfinished ...>
4996  <... futex resumed> )             = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
4997  <... kill resumed> )              = 0
4996  --- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_USER, si_pid=4996, si_uid=1000} ---
4996  write(7, "\1", 1)                 = 1
4996  rt_sigreturn({mask=[]})           = -1 EINTR (Interrupted system call)
4997  epoll_wait(3,  <unfinished ...>
4996  futex(0x7fab2d422034, FUTEX_WAIT_BITSET_PRIVATE, 1, {681000, 511223970}, ffffffff <unfinished ...>
4997 <... epoll_wait resumed> [{EPOLLIN|EPOLLOUT, {u32=0, u64=0}}], 1024, 0) = 1
```

This may be exposing a different bug? I think it all has to do with the oddness or reregistering the same fd. I forget why that happened in the first place, but it definitely seems like it's causing issues :(

**Comment by alexcrichton** [comment]
Bah CI is still failing :(

**Comment by ipetkov** [comment]
I got a local repro working (I think I had an older snapshot checked out before [doh!]), so I'll debug when I get the chance!

**Comment by ipetkov** [comment]
Okay, I think I found a work around for the test case (findings documented in #38). I noticed that on linux some of the other test cases will randomly deadlock, but running with a single test thread fixes things (this may be due to my VM setup, but I'll open a separate PR to refactor the tests into their own integration style test in case there is weird interaction between concurrently running tests)

**Comment by ipetkov** [comment]
@alexcrichton whew CI is finally passing and ready for another review :)

I've opened a few follow up tasks (#38 and #39), though I do recommend blocking the next release on fixing #38 since that's likely to cause all kinds of headaches

**Comment by ipetkov** [comment]
@alexcrichton Squashed and rebased!
